
**Numpy: Basic Definition and Uses**
![NumPy Logo](https://numpy.org/doc/stable/_static/numpylogo_dark.svg)
---

Numpy (Numerical Python) ek Python library hai jisko scientific computing mein use kiya jaata hai. Yeh multidimensional array objects, matrices, aur inpe kaam karne wale functions provide karta hai.


---



*   Maths calculations: Numpy maths calculations ko easy aur fast banata hai, khaaskar bade datasets ke saath. Isme linear algebra, Fourier transform, random number generation jaise bahut saare useful functions hain.
* Data Science: Numpy, pandas aur matplotlib jaise data science libraries ka base hai. Data manipulation, analysis, aur visualization ke liye iska use kiya jaata hai.
* Arrays: Numpy ka main feature array hai, jo Python lists se zyada efficient hota hai. Array mein ek hi type ka data store kiya jaata hai, jisse operations tezi se hote hain.
* Machine Learning: Machine learning algorithms ko implement karne ke liye Numpy ka use kiya jaata hai. Data preprocessing, feature engineering, aur model training mein yeh madad karta hai.
---
In short, Numpy ek powerful library hai jo scientific computing, data science, aur machine learning mein useful hai. Yeh maths calculations ko easy aur fast banata hai aur data ko manage karne ke liye efficient tools provide karta hai.



In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
# create a list
l_1=[0,1,2,3,4,5,6]

# print the list with data type
print(f"list={l_1} and data type is {type(l_1)}")

list=[0, 1, 2, 3, 4, 5, 6] and data type is <class 'list'>


In [ ]:
# list convert the numpy array
np_arr=np.array(l_1)
# print the numpy array with data type
print(f'numpy array {np_arr} data type is {type(np_arr)}')
# more  method to create a arry like  `asarray and asanyarray`

numpy array [0 1 2 3 4 5 6] data type is <class 'numpy.ndarray'>


# fromfunction

fromfunction ek NumPy array banata hai jiske values ek function se generate hote hain. Yeh function array ke har element ke coordinates leta hai aur ek value return karta hai jo uss element mein daali jaati hai.

Basically, yeh ek function use karke automatically array create karta hai.

Think of it like:

Blank grid (array)
Function = painter
Coordinates = box location
Returned value = color of the box
Hope this short definition helps! 😉

In [3]:
import numpy as np

In [4]:
def my_func(x:int, y:int) :
   return x + y
x=2
y=2
# arr_2=np.fromfunction(my_func, shape=(3,3), dtype=int)
arr_2=np.fromfunction(lambda i, j: my_func(i+x, y+j), shape=(3,3))

In [ ]:
print(arr_2)

[[4. 5. 6.]
 [5. 6. 7.]
 [6. 7. 8.]]




> Pehle element ke liye (0, 0), my_func(0, 0, 2, 3) calculate hota hai 0.

> Dusre element ke liye (0, 1), my_func(0, 1, 2, 3) calculate hota hai 3.






In [ ]:
def my_func(x, y, a, b):
    return a * x + b * y

a = 2
b = 3
arr = np.fromfunction(lambda x, y: my_func(x, y, a, b), (3, 3), dtype=int)
print(arr)

[[ 0  3  6]
 [ 2  5  8]
 [ 4  7 10]]


# fromiter in Numpy
numpy.fromiter yeh ek NumPy array banata hai kisi bhi iterable object se. Matlab, agar tumhare paas koi list, tuple, ya generator hai, toh tum fromiter use karke usse ek array mein badal sakte ho.

Kaise kaam karta hai:

fromiter ek iterable object leta hai input mein.
Yeh iterable ke har ek item ko padhta hai, ek-ek karke.
Har item ko woh dtype mein convert karta hai jo tumne bataya hoga.
Fir yeh sab converted items ko ek naye 1-dimensional NumPy array mein store karta hai.
Aur finally, yeh bana hua array return karta hai.
Syntax:


`numpy.fromiter(iterable, dtype, count=-1)`


---


Parameters:

iterable: Yeh woh object hai jisse tum array banana chahte ho. Koi bhi list, tuple, ya generator chalega.
dtype: Yeh array mein elements ka data type hai. Tum koi bhi valid NumPy data type de sakte ho, jaise int, float, ya bool.
count: (Optional) Yeh batata hai ki iterable se kitne items read karne hain. Agar -1 hai (default), toh saare items read karega.


```
import numpy as np

# Ek iterable banao (iss case mein ek list)
iterable = [1, 2, 3, 4, 5]

# Iterable se ek NumPy array banao
array = np.fromiter(iterable, dtype=int)

# Array print karo
print(array)  # Output: [1 2 3 4 5]

```



In [ ]:
l_3=(i*87 for i in range(1,4))

In [ ]:
l_3

<generator object <genexpr> at 0x7d844e094d40>

In [ ]:
l_3_arr=np.fromiter(l_3, dtype=int)
print(l_3_arr)

[ 87 174 261]


# Fromstring()


---
numpy.fromstring() method ek naya 1-dimensional array banata hai ek string se jisme numerical data hota hai. Matlab, yeh ek string leta hai jo numbers ko represent karta hai aur usko NumPy array mein convert karta hai.



---



```
numpy.fromstring(string, dtype=float, sep='', *, count=-1, like=None)

```
> Parameters:

string: Yeh input string hai jisme numerical data hai.

dtype: Yeh array ke elements ka desired data type hai (e.g., int, float).
Default float hai.

sep: Yeh delimiter hai jo string mein values ko alag karta hai. Default koi bhi whitespace hai.

count: (Optional) Kitne values string se read karne hain. Agar -1 hai (default), toh saare values read karega.

like: (Optional) Existing array ke properties se array define karne ke liye use hota hai.

---
> Kaise kaam karta hai:

fromstring() method input string leta hai.

Yeh sep parameter use karke string mein numerical values ke beech ke delimiters ko identify karta hai.

Yeh har value ko specified dtype mein convert karta hai.

Yeh ek naya 1-dimensional NumPy array banata hai jisme yeh converted values hote hain.

Finally, yeh bana hua array return karta hai.

```
import numpy as np

# Comma-separated values wali string se array banao
data_string = "1,2,3,4,5"
array = np.fromstring(data_string, dtype=int, sep=",")

# Output dekhne ke liye code run karo.
# Expected output: [1 2 3 4 5]
```



In [ ]:
data_str="1,2,3,4,5"
data_str_1=np.fromstring(data_str,sep=",", dtype=int)
print(data_str_1)

data_str_2="100 200 300 500"
data_str_3=np.fromstring(data_str_2,sep=" ", dtype=int)
print(data_str_3)

[1 2 3 4 5]
[100 200 300 500]


# COPY


---



> Shallow Copy:

Ek naya array object banta hai, lekin yeh original array ke data ko point karta hai.
Matlab, agar tum shallow copy mein kuch change karte ho, toh woh original array mein bhi reflect hoga.
Socho ise ek photocopy ki tarah, jahan original aur copy dono same data share karte hain.
`view()` method use karke shallow copy banate hain.

---

> Deep Copy:

Ek naya array object banta hai aur original array ke data ki ek independent copy bhi banti hai.
Matlab, agar tum deep copy mein kuch change karte ho, toh woh original array ko affect nahin karega.
Socho ise original document ki ek nayi copy ki tarah, jahan dono independent hain.
`copy()` method use karke deep copy banate hain.

---
In short:

Shallow copy: Data share karta hai, changes dono mein reflect hote hain.
Deep copy: Data ki independent copy, changes ek dusre ko affect nahin karte.




In [ ]:
data_arr=[1,2,3,4,5,6]
#create a shallow copy
data_arr_s=data_arr

print('original',data_arr)

# change first index
data_arr_s[0]=100
print("copy shallow",data_arr_s)
print('original changed',data_arr)

original [1, 2, 3, 4, 5, 6]
copy shallow [100, 2, 3, 4, 5, 6]
original changed [100, 2, 3, 4, 5, 6]


In [ ]:
# create a deep Copy
data_arr_d=data_arr.copy()

print('original',data_arr)

data_arr_d[0]=1000
print("copy deep",data_arr_d)
print('original not changed',data_arr)

original [100, 2, 3, 4, 5, 6]
copy deep [1000, 2, 3, 4, 5, 6]
original not changed [100, 2, 3, 4, 5, 6]


# Numpy Data Types

In [ ]:
# Create an integer list
integer_list = [10, 20, 30, 40, 50]

print(f"Integer list: {integer_list}")

print(f"Data type of integer_list: {type(integer_list)}")

Integer list: [10, 20, 30, 40, 50]
Data type of integer_list: <class 'list'>


In [ ]:
# Convert the list to a NumPy array
integer_array = np.array(integer_list)

print(f"Integer array: {integer_array}")
print(f"Data type of integer_array: {type(integer_array)}")
print(f"Data type of elements in integer_array: {integer_array.dtype}")

Integer array: [10 20 30 40 50]
Data type of integer_array: <class 'numpy.ndarray'>
Data type of elements in integer_array: int64


In [ ]:
integer_array.ndim
# [10 20 30 40 50] only one row

1

In [ ]:
ar_2=np.asarray([[1,2,3],[9,9,9]])
print(f"two dimensional array: {ar_2}")
print(f"Data type of ar_2: {type(ar_2)}")
print(f"Data type of elements in ar_2: {ar_2.dtype}")

two dimensional array: [[1 2 3]
 [9 9 9]]
Data type of ar_2: <class 'numpy.ndarray'>
Data type of elements in ar_2: int64


In [ ]:
ar_2

array([[1, 2, 3],
       [9, 9, 9]])

In [ ]:
ar_2.ndim

2

In [ ]:
ar_3=np.array([
    [1,2,3],
    [0,9,8],
    [6,6,5]
])

In [ ]:
ar_3

array([[1, 2, 3],
       [0, 9, 8],
       [6, 6, 5]])

In [ ]:
ar_3.ndim

2

In [ ]:
ar_4=np.array(
    [
        [
            [1,2,3],
            [0,9,8],
            [6,6,5]
        ],
    ]
)

In [ ]:
ar_4

array([[[1, 2, 3],
        [0, 9, 8],
        [6, 6, 5]]])

In [ ]:
ar_4.ndim

3

In [ ]:
ar_4.shape

(1, 3, 3)

# Arange() in Numpy
- ab hum ma range function ka use kar ka 0 sa 5.4 tak ki range ka array bana hai
- ak tu ya range function float value ko support nahi karta is liya hum numpy ka

```
np.arange()
```
- method use karta hai

- Pehla parameter batata hai ki tum kahan se shuru karoge (starting point).

- Dusra parameter batata hai ki tum kahan tak jaoge (ending point).
- Teesra parameter, jisko hum "step size" kehte hain, batata hai ki tum kitne steps skip karoge har baar.

In [9]:
val_1=np.arange(0,5.4,0.5)
print(val_1)
print(type(val_1))

val_2=np.arange(0,5.4,.5)
print(val_2)
print(type(val_2))

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]
<class 'numpy.ndarray'>
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]
<class 'numpy.ndarray'>


# linspace() in Numpy
- linsapace three parameter lata hai first kaha sa start ho ga second kaha take jaye ga or third jo is ki khasiyat hai 0 sa 5 ka bechema 20 numbers batao
---
```
np.linspace("firstNum,secondNum,ThirdNum")
```



In [11]:
val_3=np.linspace(1,3,50)
print(val_3)
print(type(val_3))

[1.         1.04081633 1.08163265 1.12244898 1.16326531 1.20408163
 1.24489796 1.28571429 1.32653061 1.36734694 1.40816327 1.44897959
 1.48979592 1.53061224 1.57142857 1.6122449  1.65306122 1.69387755
 1.73469388 1.7755102  1.81632653 1.85714286 1.89795918 1.93877551
 1.97959184 2.02040816 2.06122449 2.10204082 2.14285714 2.18367347
 2.2244898  2.26530612 2.30612245 2.34693878 2.3877551  2.42857143
 2.46938776 2.51020408 2.55102041 2.59183673 2.63265306 2.67346939
 2.71428571 2.75510204 2.79591837 2.83673469 2.87755102 2.91836735
 2.95918367 3.        ]
<class 'numpy.ndarray'>


In [17]:
# zeros method ya method array ma sirf zero hi store karta hai
# example [
#     [0,0,0],
#     [0,0,0],
#     [0,0,0],
# ]

val_4=np.zeros((3,13), dtype=int)
print(val_4)

[[0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [20]:
# ab hun 3d dimensinal array bana hai simple
val_5=np.zeros((3,3,3), dtype=int)
print(val_5)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


In [22]:
# lets create 4d array
val_6=np.zeros((3,3,3,3))
print(val_6)

[[[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]


 [[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]


 [[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]]


In [31]:
# zeros to upgrade version is onces() its converd the whole array in 1 number
'''
example
[
  [1,1,1,1],
  [1,1,1,1],
  [1,1,1,1],
  [1,1,1,1],
]
'''
val_7=np.ones((3,2,3,3), dtype=int)
print(val_7)
print(f'check dimension {val_7.ndim}')

[[[[1 1 1]
   [1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]]]


 [[[1 1 1]
   [1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]]]


 [[[1 1 1]
   [1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]]]]
check dimension 4


In [32]:
val_8=val_7+32/10*78

In [33]:
print(val_8)

[[[[250.6 250.6 250.6]
   [250.6 250.6 250.6]
   [250.6 250.6 250.6]]

  [[250.6 250.6 250.6]
   [250.6 250.6 250.6]
   [250.6 250.6 250.6]]]


 [[[250.6 250.6 250.6]
   [250.6 250.6 250.6]
   [250.6 250.6 250.6]]

  [[250.6 250.6 250.6]
   [250.6 250.6 250.6]
   [250.6 250.6 250.6]]]


 [[[250.6 250.6 250.6]
   [250.6 250.6 250.6]
   [250.6 250.6 250.6]]

  [[250.6 250.6 250.6]
   [250.6 250.6 250.6]
   [250.6 250.6 250.6]]]]


In [ ]:
'''
[[1, 0, 0],
 [0, 1, 0],
 [0, 0, 1]]

Dekho, diagonal par 1 hain aur baaki jagah 0 hain.

Simple words mein: eye() method se hum ek special matrix banate hain jisme diagonal par 1 hote hain aur baaki jagah 0 hote hain.

Kya kaam aata hai?

Identity matrix ka use bahut saare mathematical calculations mein hota hai, jaise:

Linear algebra
Matrix operations
Machine learning algorithms
'''

In [41]:
val_9=np.eye(20, dtype=int, k=8)
print(val_9)

[[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [50]:
# logspace
'''
Is function mein teen parameters hain:

start (2): Yeh sequence ka starting point hai. Yahaan se values generate hona shuru hongi.
 Is case mein, starting point 2 hai.
stop (5): Yeh sequence ka ending point hai. Values generate hote hue is point tak jaayengi.
 Is case mein, ending point 5 hai.
base (2): Yeh logarithm ka base hai. Is case mein, base 2 hai. Default base 10 hota hai,
lekin yahaan humne use 2 specify kiya hai.
Kya hoga is function se?

Yeh function ek array generate karega jisme values base ** start se base ** stop tak
logarithmically spaced hongi. Yahaan, ** ka matlab exponent hai.

Is case mein, function yeh array generate karega:


[4. 8. 16. 32.]
Use code with caution
Explanation:

Pehli value: 2 ** 2 = 4
Dusri value: 2 ** 3 = 8
Teesri value: 2 ** 4 = 16
Chauthi value: 2 ** 5 = 32
Yeh values 2 ke base mein logarithmically spaced hain, matlab har value pichli
value se 2 guna badh rahi hai.

Simple words mein:

np.logspace(2, 5, base=2) ek array generate karta hai jisme values 4 se 32 tak
hoti hain aur har value pichli value se 2 guna badh rahi hoti hai.
------------------------------------------------------------------------------------
num parameter: Yeh specify karta hai ki array mein kitne values generate karne hain.
 Agar num parameter specify nahi kiya jaata, toh iski default value 50 hoti hai.

Is case mein, humne num parameter specify nahi kiya, isliye function ne 50 values
generate kiye hain jo 4 se 32 tak logarithmically spaced hain.

Agar aap output mein sirf 4 values chahte hain, toh aapko num parameter ko 4 specify
karna hoga:


np.logspace(2, 5, base=2, num=4)
Use code with caution
Isse aapko yeh output milega:


[ 4.  8. 16. 32.]
Use code with caution
Simple words mein:

np.logspace() function default olarak 50 values generate karta hai.
Agar aap kam ya zyada values chahte hain, toh aapko num parameter use karna hoga.

Umeed hai ab yeh clear hai! Agar koi aur sawal hai to pooch sakte ho.
'''

val_10=np.logspace(2,6 ,base=2, num=4)
print(val_10)

[ 4.         10.0793684  25.39841683 64.        ]


In [51]:
np.arange(4)/3

array([0.        , 0.33333333, 0.66666667, 1.        ])

# Random() Method in Numpy

In [54]:
arr_1=np.random.rand(5,4)

In [55]:
arr_1

array([[0.86073482, 0.13826211, 0.95052007, 0.84729001],
       [0.0235748 , 0.15467744, 0.29834908, 0.02742945],
       [0.39413021, 0.14684008, 0.58002385, 0.38881828],
       [0.82555033, 0.28479872, 0.45449055, 0.4590166 ],
       [0.57679917, 0.00816333, 0.83946112, 0.28024973]])

In [57]:
arr_2=np.random.randint(2,10,(4,4))
arr_2

array([[9, 8, 5, 8],
       [8, 2, 4, 8],
       [8, 2, 6, 7],
       [8, 5, 3, 8]])

In [58]:
import pandas as pd


In [ ]:
arr_3=a=pd.DataFrame(np.random.randint(2,10,(40,40)))
arr_3

In [64]:
arr_3.to_csv("random-data.csv")

In [73]:
# reshape the array
arr_2
print(arr_2.shape)

(4, 4)


# Indexing and Slicing Numpy

In [77]:
arr_1

array([[0.86073482, 0.13826211, 0.95052007, 0.84729001],
       [0.0235748 , 0.15467744, 0.29834908, 0.02742945],
       [0.39413021, 0.14684008, 0.58002385, 0.38881828],
       [0.82555033, 0.28479872, 0.45449055, 0.4590166 ],
       [0.57679917, 0.00816333, 0.83946112, 0.28024973]])

In [78]:
arr_1[0]

array([0.86073482, 0.13826211, 0.95052007, 0.84729001])

In [79]:
arr_1[0][2]

0.9505200660652796

In [82]:
arr_1[2, [2,3]]

array([0.58002385, 0.38881828])

In [83]:
arr_5=np.random.randint(1,10,(3,3,3))

In [84]:
arr_5

array([[[1, 3, 4],
        [8, 5, 7],
        [5, 2, 7]],

       [[7, 7, 4],
        [5, 1, 1],
        [5, 9, 3]],

       [[4, 8, 9],
        [8, 3, 8],
        [4, 8, 6]]])

In [85]:
arr_5[2]

array([[4, 8, 9],
       [8, 3, 8],
       [4, 8, 6]])

In [86]:
arr_5[2][1][2]

8

In [89]:
# comperishion
arr_5[arr_5>7]

array([8, 9, 8, 9, 8, 8, 8])

In [90]:
arr_5+23

array([[[24, 26, 27],
        [31, 28, 30],
        [28, 25, 30]],

       [[30, 30, 27],
        [28, 24, 24],
        [28, 32, 26]],

       [[27, 31, 32],
        [31, 26, 31],
        [27, 31, 29]]])

In [91]:
arr_5/10

array([[[0.1, 0.3, 0.4],
        [0.8, 0.5, 0.7],
        [0.5, 0.2, 0.7]],

       [[0.7, 0.7, 0.4],
        [0.5, 0.1, 0.1],
        [0.5, 0.9, 0.3]],

       [[0.4, 0.8, 0.9],
        [0.8, 0.3, 0.8],
        [0.4, 0.8, 0.6]]])

In [92]:
arr_5-10

array([[[-9, -7, -6],
        [-2, -5, -3],
        [-5, -8, -3]],

       [[-3, -3, -6],
        [-5, -9, -9],
        [-5, -1, -7]],

       [[-6, -2, -1],
        [-2, -7, -2],
        [-6, -2, -4]]])

# Real Multiplication of Matrix

In [93]:
arr_1

array([[0.86073482, 0.13826211, 0.95052007, 0.84729001],
       [0.0235748 , 0.15467744, 0.29834908, 0.02742945],
       [0.39413021, 0.14684008, 0.58002385, 0.38881828],
       [0.82555033, 0.28479872, 0.45449055, 0.4590166 ],
       [0.57679917, 0.00816333, 0.83946112, 0.28024973]])

In [94]:
arr_2

array([[9, 8, 5, 8],
       [8, 2, 4, 8],
       [8, 2, 6, 7],
       [8, 5, 3, 8]])

In [95]:
arr_1 @ arr_2

array([[23.23519089, 13.29989295, 13.10171297, 21.423936  ],
       [ 4.0558209 ,  1.23179864,  2.60896656,  3.73389702],
       [12.47262961,  6.55086099,  7.20460932, 11.49847555],
       [17.01640002, 10.37806423,  9.37093968, 15.73635914],
       [14.21418595,  7.71089088,  8.79416507, 12.79792566]])