## Linear Regression From Scratch

In [8]:
import numpy as np
import pandas as pd


In [5]:
import seaborn as sns


In [44]:
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression



df=make_regression(n_samples=1000, n_features=2, noise=20)


X=pd.DataFrame(df[0])
y=pd.DataFrame(df[1])


X_train , X_test, Y_train, Y_test=train_test_split(X, y, test_size=0.2, random_state=42)

In [40]:
X.columns=['x1', 'x2']
y.columns=['y']

In [41]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   x1      1000 non-null   float64
 1   x2      1000 non-null   float64
dtypes: float64(2)
memory usage: 15.8 KB


In [61]:
class LinearRegressionScratch():

  def __init__(self, fit_intercept):
    self.fit_intercept=fit_intercept
    self.coef_=None   # weights (w1, w2, ..., wp)
    self.bias=0 # bias means intercept value
    self.n_features=None
    self.is_fitted=False # means model its not train this time its true is_fitted = True

  def fit(self,X, y):
    x=np.array(X, np.float64)
    y=np.array(y, np.float64).flatten()

    n_samples,input_features=x.shape
    self.n_features=input_features

    if self.fit_intercept:
      x_aug=np.column_stack((x, np.ones(n_samples)))
      theta=self._solve_normal_equation(x_aug, y)
      self.bias=theta[-1] # The last element is the intercept
      self.coef_=theta[:-1] # All elements except the last are coefficients

      # print(theta[0], '0f')
      # print(theta[1:], 'og')
      print(theta, '0h')
    else:
      theta=self._solve_normal_equation(x, y)
      self.bias_=20
      self.coef_=theta

    self.is_fitted=True
    return self


  def _solve_normal_equation(self, X, y):
      # print(f"[DEBUG] Solving Normal Equation for X shape {X.shape}, y shape {y.shape}")

      # step no 1

      xtx= X.T @ X
      # print(f"[DEBUG] xtx shape {xtx.shape}")
      # print(f'[DEBUG] xtx shape {xtx}')

      # step no 2

      xty= X.T @ y
      # print(f"[DEBUG] xty shape {xty.shape}")
      # print(f'[DEBUG] xty shape {xty}')

      #step no 3

      try:
        Xtx_inv = np.linalg.inv(xtx)
        # print(f"[DEBUG] Xtn shape {Xtx_inv.shape}")
        # print(f'[DEBUG] Xtn shape {Xtx_inv}')
        # print(f"[DEBUG] (X^T X)^(-1) computed successfully.")
      except np.linalg.LinAlgError:
        raise ValueError("Matrix X^T X is singular (not invertible). "
                             "Try reducing features or adding regularization.")

      theta=Xtx_inv @ xty
      # print(f"[DEBUG] theta shape {theta.shape}")/
      print(f'[DEBUG] theta shape {theta} weights')
      return theta

  def pridict(self, X):


      X=np.array(X, np.float64)
      # n_samples= X.shape[0] # This is not needed here

      y_pred=X @ self.coef_ + self.bias # Corrected the prediction calculation
      print(f'[DEBUG] y_pred shape {y_pred[:5]}')
      return y_pred




model=LinearRegressionScratch(fit_intercept=True)
model.fit(X_train, Y_train)

sk_model=LinearRegression()
sk_model.fit(X_train, Y_train)

Y_predict=model.pridict(X_test)
Y_predict_sk=sk_model.predict(X_test)

mse=mean_squared_error(Y_test, Y_predict)
mse_sk=mean_squared_error(Y_test, Y_predict_sk)

r2=r2_score(Y_test, Y_predict)
r2_sk=r2_score(Y_test, Y_predict_sk)

print(mse, mse_sk)
print(r2, r2_sk)

[DEBUG] theta shape [69.11350903 96.01502143  0.15430391] weights
[69.11350903 96.01502143  0.15430391] 0h
[DEBUG] y_pred shape [-103.25209659 -138.8667685  -353.92106503   26.2794458   -61.4072932 ]
429.9107635595472 429.9107635595472
0.9716018582384619 0.9716018582384619


- `np.column_stack()` expects a tuple or list of arrays with matching dimensions along the non-concatenation axis.
- To stack the arrays horizontally, ensure they have the same number of rows.
- Example with arrays of the same size:



```
array([[34.,  1.],
       [35.,  1.],
       [36.,  1.]])
```



In [32]:
# `np.column_stack()` expects a tuple or list of arrays with matching dimensions along the non-concatenation axis.
# To stack the arrays horizontally, ensure they have the same number of rows.
# Example with arrays of the same size:
np.column_stack((np.array([34, 35, 36]), np.ones(3)))

array([[34.,  1.],
       [35.,  1.],
       [36.,  1.]])

In [56]:
X_test

,0,1
521,-0.597959,-0.646559
737,-0.566445,-1.040171
740,-0.685404,-3.194341
660,1.033793,-0.472050
411,-1.273556,0.275565
...,...,...
408,-1.320728,0.504677
332,0.957410,0.397417
208,-1.052336,-0.916109
613,-0.318514,0.270191
