### Import the Importtant modules

In [2]:
import numpy as np
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.metrics import mean_squared_error, r2_score

In [3]:
X, Y=make_regression(n_samples=100, n_features=10, noise=0.1, random_state=40)

In [4]:
X.shape

(100, 10)

In [ ]:
Y.shape


(100,)

In [6]:
X

array([[-2.94246190e-01, -1.15835891e+00,  7.44560800e-01,
         9.23707227e-01, -1.70149469e-01,  2.07998152e-01,
         1.20454594e+00,  7.36879035e-01,  1.00699087e-01,
         1.68503356e-01],
       [ 1.26492990e-01,  3.42900890e-02,  8.06940890e-01,
        -8.91310634e-01, -6.45567815e-02, -8.48434311e-01,
        -1.36263295e-01, -1.74137720e+00,  2.68831363e-01,
        -1.54794096e-01],
       [ 3.27784701e-01, -4.21372691e-01,  1.15975977e+00,
        -3.24009925e-01, -8.07252821e-01,  2.21474838e-01,
        -2.05723245e-01,  1.10721109e+00,  1.95613611e-01,
         6.58698549e-01],
       [ 1.62417611e+00, -9.95180407e-01, -2.07753518e-01,
        -4.28434490e-01, -6.02782195e-02, -7.47163259e-01,
        -9.67559187e-01, -8.16097543e-01,  5.43699020e-01,
        -2.47595994e-01],
       [ 3.23757000e-01,  1.98513282e-01,  9.20259071e-01,
         1.47192834e+00,  1.09636305e+00, -1.36070055e-01,
        -2.31627400e-01,  1.02183118e+00,  1.56549229e+00,
        -1.

### Split the data into traning and test data

In [7]:
x_train, x_test, y_tran , y_test= train_test_split(X, Y, test_size=0.2, random_state=40)

In [8]:
x_train.shape

(80, 10)

## Train the Model for Train Dataset

In [9]:
linear_reg=LinearRegression()

In [10]:
linear_reg.fit(x_train, y_tran)

LinearRegression()

In [11]:
y_preditc_value=linear_reg.predict(x_test)

In [12]:
y_preditc_value

array([ -45.99304072, -109.56926819,   22.17988467,   51.81445022,
        163.22819128,  199.24731621,   34.80450545, -134.49949271,
         25.22038411,  -49.19995897,   49.05165481,   92.72191027,
        319.01734048, -110.43819074,  -59.41749102, -214.04854113,
       -118.70556532,   42.3179794 , -226.39567222,  248.85512815])

In [13]:
y_test


array([ -45.9007582 , -109.71147906,   22.20833289,   51.74576069,
        163.20982414,  199.19803565,   34.79262614, -134.52259242,
         25.35071011,  -49.31194822,   48.98058586,   92.69110702,
        319.09298781, -110.24688462,  -59.41496021, -214.09322204,
       -118.69013956,   42.29493851, -226.30280643,  248.73850489])

In [14]:
# mean squared error value
linear_reg_mse=mean_squared_error(y_test, y_preditc_value)
linear_reg_r2=r2_score(y_test, y_preditc_value)
print(
linear_reg_mse
)

print(linear_reg_r2)

0.007027574639809739
0.9999996552426447


## Ridge Regression

In [18]:
ridge_reg=Ridge(alpha=0.1)
ridge_reg.fit(x_train, y_tran)
Y_prediction_reg=ridge_reg.predict(x_test)
ridge_reg_mse=mean_squared_error(y_test, Y_prediction_reg)
ridge_r2=r2_score(y_test, Y_prediction_reg)

print(ridge_reg_mse)
print(ridge_r2)

0.04020517765607133
0.999998027622412


In [16]:
y_test

array([ -45.9007582 , -109.71147906,   22.20833289,   51.74576069,
        163.20982414,  199.19803565,   34.79262614, -134.52259242,
         25.35071011,  -49.31194822,   48.98058586,   92.69110702,
        319.09298781, -110.24688462,  -59.41496021, -214.09322204,
       -118.69013956,   42.29493851, -226.30280643,  248.73850489])

In [17]:
Y_prediction_reg

array([ -45.89690487, -109.40796666,   22.00659813,   51.57003467,
        163.11545854,  198.90953026,   35.01229636, -134.26945664,
         25.27187772,  -49.23559411,   48.94933797,   92.63271044,
        318.73268872, -110.16120967,  -59.31371516, -213.74021855,
       -118.51053945,   42.19592699, -226.08144006,  248.50100093])